TOPIC_BLUEPRINTS = [
    {
        "name": "Linked List",
        "slug": "linked-list",
        "description": "Learn about linear data structures with pointers.",
        "short_description": "Struktur data berantai antar node.",
        "difficulty": "Beginner",
        "icon": "linked-list",
        "duration": "~2 hours",
        "exercises": 20,
        "recommended": True,
        "locked": False,
        "status": "in-progress",
        "progress": 45,
        "avg_score": 48,
        "accuracy": 55,
        "last_accessed_days_ago": 3,
        "chart_color": "#5F6AF4",
    },
    {
        "name": "Stack",
        "slug": "stack",
        "description": "Master LIFO (Last In First Out) data structure.",
        "short_description": "Struktur data dengan prinsip LIFO.",
        "difficulty": "Beginner",
        "icon": "stack",
        "duration": "~2 hours",
        "exercises": 20,
        "recommended": False,
        "locked": False,
        "status": "beginner",
        "progress": 80,
        "avg_score": 71,
        "accuracy": 84,
        "last_accessed_days_ago": 1,
        "chart_color": "#7A55EC",
    },
    {
        "name": "Queue",
        "slug": "queue",
        "description": "Understand FIFO (First In First Out) operations.",
        "short_description": "Struktur data dengan prinsip FIFO.",
        "difficulty": "Beginner",
        "icon": "queue",
        "duration": "~2 hours",
        "exercises": 20,
        "recommended": False,
        "locked": False,
        "status": "beginner",
        "progress": 60,
        "avg_score": 65,
        "accuracy": 74,
        "last_accessed_days_ago": 2,
        "chart_color": "#D24F9C",
    },
    {
        "name": "Tree",
        "slug": "tree",
        "description": "Explore hierarchical data structures.",
        "short_description": "Pelajari traversal dan relasi parent-child.",
        "difficulty": "Intermediate",
        "icon": "tree",
        "duration": "~2 hours",
        "exercises": 20,
        "recommended": False,
        "locked": False,
        "status": "intermediate",
        "progress": 25,
        "avg_score": 33,
        "accuracy": 40,
        "last_accessed_days_ago": 8,
        "chart_color": "#ED9D28",
    },
    {
        "name": "Graph",
        "slug": "graph",
        "description": "Study networks and connections.",
        "short_description": "Pahami relasi node dan edge lebih kompleks.",
        "difficulty": "Advanced",
        "icon": "graph",
        "duration": "~2 hours",
        "exercises": 20,
        "recommended": False,
        "locked": True,
        "status": "locked",
        "progress": 10,
        "avg_score": 21,
        "accuracy": 26,
        "last_accessed_days_ago": 12,
        "chart_color": "#42B883",
    },
    {
        "name": "Sorting Algorithms",
        "slug": "sorting",
        "description": "Learn different sorting techniques.",
        "short_description": "Bandingkan strategi sorting dan kompleksitasnya.",
        "difficulty": "Intermediate",
        "icon": "sorting",
        "duration": "~2 hours",
        "exercises": 20,
        "recommended": False,
        "locked": True,
        "status": "locked",
        "progress": 50,
        "avg_score": 20,
        "accuracy": 29,
        "last_accessed_days_ago": 6,
        "chart_color": "#4D7DE0",
    },
]

TOPIC_BLUEPRINTS_BY_NAME = {
    topic["name"]: topic for topic in TOPIC_BLUEPRINTS
}
